Repository wrightedu/CSE-Discord-Bot, pull requests merged in 2021-07, with the labels that each got.

#69 displaying corgi image number
  Cogs/StudentCommands.py
Labels: enhancement

#71 Attendance Command
  Cogs/StudentCommands.py
  bot.py
Labels: enhancement

#70 Minor New Features & Cloudformation Copy
  CSEdiscord.yml
  Cogs/Listeners.py
  Cogs/StudentCommands.py
  bot.py
Labels: enhancement

#73 Public documentation
  ARCHITECTURE.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#74 Public Documentation
  ARCHITECTURE.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#50 Docstrings following the Google Docstring format have been added to most methods of the cogs within the discord bot
  .gitignore
  Cogs/AdminCommands.py
  Cogs/CogManagement.py
  Cogs/Listeners.py
  Cogs/ServerManagement.py
  Cogs/StudentCommands.py
  bot.py
  utils.py
Labels: documentation

#81 Issue 80 - Handling Out of Bound Errors for Corgme
  Cogs/StudentCommands.py
Labels: bot bug

#82 Issue78
  Cogs/StudentCommands.py
  helloworld.yml
Labels: enhancement

#84 Issue 78 - Read languages from yaml
  Cogs/StudentCommands.py
  helloworld.yml
Labels: enhancement

#85 Merge new features to master
  Cogs/StudentCommands.py
  helloworld.yml
Labels: enhancement
