Repository wrightedu/CSE-Discord-Bot, pull requests merged in 2022-08, with the labels that each got.

#154 Import from Utils fix
  Cogs/AdminCommands.py
  Cogs/CogManagement.py
  Cogs/CourseManagement.py
  Cogs/Faq.py
  Cogs/Gourmet.py
  Cogs/Listeners.py
  Cogs/StudentCommands.py
Labels: CRITICAL

#166 Fixed an error to DestroyCourses
  Cogs/CourseManagement.py
Labels: bot bug

#165 Updated buildcourses
  Cogs/CourseManagement.py
Labels: enhancement
